version: "2"

services:
  mongo:
    image: mongo:2.6.12
    ports:
    - "27017:27017"
    volumes:
    - mongo-data:/data/db
    - mongo-config:/data/configdb

  user:
    build: user/target/docker
    ports:
    - "8000:8080"
    links:
    - mongo

volumes:
  mongo-data:
    external: false

  mongo-config:
    external: false